In [15]:
import pandas as pd
df = pd.read_csv('./data/gapminder.tsv',sep='\t') #.은 현재 파일, /는 그 밑에 폴더

In [14]:
type(df)

pandas.core.frame.DataFrame

In [27]:
df

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [191]:
print(f'행 갯수는 {df.shape[0]}')
print(f'열 갯수는 {df.shape[1]}')
df.shape

행 갯수는 1704
열 갯수는 6

(1704, 6)

In [48]:
df.columns # 칼럼명

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [51]:
df.index

RangeIndex(start=0, stop=1704, step=1)

In [52]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

In [57]:
df.head(3) # 맨 앞 다섯줄

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710

In [60]:
df.tail(3) #맨끝에서 다섯줄

       country continent  year  lifeExp       pop   gdpPercap
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [192]:
df.year.unique() # year:칼럼명, 중복값 제외

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

In [78]:
# df['country'] #시리즈타입(세로방향 인덱스, 1차원) 정식형식 추천
df.country #약칭형식, 안 먹는 경우도 있음

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: object

In [74]:
df[ ['country'] ] #DataFrame타입(칼럼명이 붙음, 2차원)

          country
0     Afghanistan
1     Afghanistan
2     Afghanistan
3     Afghanistan
4     Afghanistan
...           ...
1699     Zimbabwe
1700     Zimbabwe
1701     Zimbabwe
1702     Zimbabwe
1703     Zimbabwe

[1704 rows x 1 columns]

In [84]:
df.loc[ 3 ]

country      Afghanistan
continent           Asia
year                1967
lifeExp            34.02
pop             11537966
gdpPercap     836.197138
Name: 3, dtype: object

In [93]:
df.loc[ 3 ]['year']

np.int64(1967)

In [101]:
df.loc[ [0,3,5] ]

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
5  Afghanistan      Asia  1977   38.438  14880372  786.113360

In [90]:
df.loc[ [0,3,5] ]['year']

0    1952
3    1967
5    1977
Name: year, dtype: int64

In [94]:
df.loc[ [0,3,5] ]['year'][5] #display함수라 타입도 함께 표시

np.int64(1977)

In [95]:
df.iloc[ [0,3,5] ]

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
5  Afghanistan      Asia  1977   38.438  14880372  786.113360

In [106]:
df.iloc[ -1 ] #음수 적용 가능

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [105]:
df.loc[ [5,0,3] ].iloc[0] #앞의 loc의 리스트의 순번상 0번 추출 = iloc사용

country      Afghanistan
continent           Asia
year                1977
lifeExp           38.438
pop             14880372
gdpPercap      786.11336
Name: 5, dtype: object

In [108]:
# df.loc[   행인덱스 , 열이름  ]
df.loc[   0 , 'year' ] #0번째 년도, 값만 뽑고싶을 때 앞에 print

np.int64(1952)

In [121]:
df1 = df.loc[ [5,55,1700],['country','year','pop'] ]

In [123]:
print(df1)

          country  year       pop
5     Afghanistan  1977  14880372
55      Argentina  1987  31620918
1700     Zimbabwe  1992  10704340

In [122]:
df1.iloc[-1]

country    Zimbabwe
year           1992
pop        10704340
Name: 1700, dtype: object

In [127]:
df.loc[ :, 'year' ] #year칼럼의 모든 행
df.loc[ 1:4, 'year' ] #year칼럼의 1~4
df.loc[ 1700:, 'year' ] #year칼럼의 1700~끝

1700    1992
1701    1997
1702    2002
1703    2007
Name: year, dtype: int64

In [135]:
df.loc[ 1, : ] #1번행 모든 칼럼
df.loc[ 1, : 'pop' ] #1번행의 처음열부터 pop열까지
df.loc[ 1, 'year' : 'pop' ] #1번행의 year열부터 pop열까지
df.loc[ 1, 'year' : ] #1번행의 year열부터 마지막열까지
df.loc[ 1:4, 'year' : 'pop' ] #1~4번행의 year열부터 pop열까지
df.loc[ [4,1,2], 'year':'pop' ] #4,1,2행 year열부터 pop열까지

   year  lifeExp       pop
4  1972   36.088  13079460
1  1957   30.332   9240934
2  1962   31.997  10267083

In [170]:
# df.loc[ 조건식 ] #조건식을 만족하는 행 추출
# b1 = df['year'] < 1960 #브로드캐스팅
df.loc[ b1 ] #Ture인 행만 추출
df.loc[ df['year'] < 1960 ] #True인 행만 추출

          country continent  year  lifeExp      pop    gdpPercap
0     Afghanistan      Asia  1952   28.801  8425333   779.445314
1     Afghanistan      Asia  1957   30.332  9240934   820.853030
12        Albania    Europe  1952   55.230  1282697  1601.056136
13        Albania    Europe  1957   59.280  1476505  1942.284244
24        Algeria    Africa  1952   43.077  9279525  2449.008185
...           ...       ...   ...      ...      ...          ...
1669  Yemen, Rep.      Asia  1957   33.970  5498090   804.830455
1680       Zambia    Africa  1952   42.038  2672000  1147.388831
1681       Zambia    Africa  1957   44.077  3016000  1311.956766
1692     Zimbabwe    Africa  1952   48.451  3080907   406.884115
1693     Zimbabwe    Africa  1957   50.469  3646340   518.764268

[284 rows x 6 columns]

In [172]:
#한국정보 찾기
# df['country']==("Korea")
r1 = df['country'].str.contains("Korea")
sum(r1)
df.loc[ r1 ]
#-------------------------------------
r1 = df['country'] == "Korea, Rep."
df.loc[ r1 ]

         country continent  year  lifeExp       pop     gdpPercap
840  Korea, Rep.      Asia  1952   47.453  20947571   1030.592226
841  Korea, Rep.      Asia  1957   52.681  22611552   1487.593537
842  Korea, Rep.      Asia  1962   55.292  26420307   1536.344387
843  Korea, Rep.      Asia  1967   57.716  30131000   2029.228142
844  Korea, Rep.      Asia  1972   62.612  33505000   3030.876650
845  Korea, Rep.      Asia  1977   64.766  36436000   4657.221020
846  Korea, Rep.      Asia  1982   67.123  39326000   5622.942464
847  Korea, Rep.      Asia  1987   69.810  41622000   8533.088805
848  Korea, Rep.      Asia  1992   72.244  43805450  12104.278720
849  Korea, Rep.      Asia  1997   74.647  46173816  15993.527960
850  Korea, Rep.      Asia  2002   77.045  47969150  19233.988180
851  Korea, Rep.      Asia  2007   78.623  49044790  23348.139730

In [175]:
#기초통계정보 (숫자형 칼럼들의)
df.describe()

             year      lifeExp           pop      gdpPercap
count  1704.00000  1704.000000  1.704000e+03    1704.000000
mean   1979.50000    59.474439  2.960121e+07    7215.327081
std      17.26533    12.917107  1.061579e+08    9857.454543
min    1952.00000    23.599000  6.001100e+04     241.165876
25%    1965.75000    48.198000  2.793664e+06    1202.060309
50%    1979.50000    60.712500  7.023596e+06    3531.846988
75%    1993.25000    70.845500  1.958522e+07    9325.462346
max    2007.00000    82.603000  1.318683e+09  113523.132900

In [178]:
df['year'].unique() #값을 중복 없이 하나씩 출력

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

In [194]:
#year가 1952인 행들만 추출
y1952 = df.loc[df['year']==1952]['lifeExp'].mean()
y1957 = df.loc[df['year']==1957]['lifeExp'].mean()
y1952, y1957

(np.float64(49.057619718309866), np.float64(51.50740112676056))

In [193]:
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64