In [18]:
import pandas as pd
df1 = pd.read_csv('./data/concat_1.csv')
df2 = pd.read_csv('./data/concat_2.csv')
df3 = pd.read_csv('./data/concat_3.csv')

In [19]:
df1

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3

In [20]:
df2

    A   B   C   D
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7

In [21]:
df3

     A    B    C    D
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [22]:
#행방향 연결
df4 = pd.concat([df1,df2,df3])
df4

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [23]:
df5 = pd.DataFrame(
    data=[["n1", "n2", "n3", "n4"]],
    columns=["A", "B", "C", "D"],
)
print(df5)

    A   B   C   D
0  n1  n2  n3  n4

In [24]:
df4 = pd.concat([df4,df5])
df4

     A    B    C    D
0   a0   b0   c0   d0
1   a1   b1   c1   d1
2   a2   b2   c2   d2
3   a3   b3   c3   d3
0   a4   b4   c4   d4
1   a5   b5   c5   d5
2   a6   b6   c6   d6
3   a7   b7   c7   d7
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11
0   n1   n2   n3   n4

In [28]:
df4 = df4.reset_index()
df4

    index    A    B    C    D
0       0   a0   b0   c0   d0
1       1   a1   b1   c1   d1
2       2   a2   b2   c2   d2
3       3   a3   b3   c3   d3
4       0   a4   b4   c4   d4
5       1   a5   b5   c5   d5
6       2   a6   b6   c6   d6
7       3   a7   b7   c7   d7
8       0   a8   b8   c8   d8
9       1   a9   b9   c9   d9
10      2  a10  b10  c10  d10
11      3  a11  b11  c11  d11
12      0   n1   n2   n3   n4

In [31]:
col_concat = pd.concat([df1, df2, df3], axis="columns", ignore_index=True) #칼럼 연결할 때는 이그노어 쓸 일이 없음
print(col_concat)

   0   1   2   3   4   5   6   7    8    9    10   11
0  a0  b0  c0  d0  a4  b4  c4  d4   a8   b8   c8   d8
1  a1  b1  c1  d1  a5  b5  c5  d5   a9   b9   c9   d9
2  a2  b2  c2  d2  a6  b6  c6  d6  a10  b10  c10  d10
3  a3  b3  c3  d3  a7  b7  c7  d7  a11  b11  c11  d11

In [34]:
df1.columns = ['A', 'B', 'C', 'D']
df2.columns = ['E', 'F', 'G', 'H']
df3.columns = ['A', 'C', 'F', 'H']
print(df1)
print(df2)
print(df3)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
    E   F   G   H
0  a4  b4  c4  d4
1  a5  b5  c5  d5
2  a6  b6  c6  d6
3  a7  b7  c7  d7
     A    C    F    H
0   a8   b8   c8   d8
1   a9   b9   c9   d9
2  a10  b10  c10  d10
3  a11  b11  c11  d11

In [35]:
row_concat = pd.concat([df1, df2, df3])
print(row_concat)

     A    B    C    D    E    F    G    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   a4   b4   c4   d4
1  NaN  NaN  NaN  NaN   a5   b5   c5   d5
2  NaN  NaN  NaN  NaN   a6   b6   c6   d6
3  NaN  NaN  NaN  NaN   a7   b7   c7   d7
0   a8  NaN   b8  NaN  NaN   c8  NaN   d8
1   a9  NaN   b9  NaN  NaN   c9  NaN   d9
2  a10  NaN  b10  NaN  NaN  c10  NaN  d10
3  a11  NaN  b11  NaN  NaN  c11  NaN  d11

In [39]:
row_concat = pd.concat([df2, df3], join='inner') #행 공통만 남김
print(row_concat)

     F    H
0   b4   d4
1   b5   d5
2   b6   d6
3   b7   d7
0   c8   d8
1   c9   d9
2  c10  d10
3  c11  d11

In [41]:
df1.index = [0, 1, 2, 3]
df2.index = [4, 5, 6, 7]
df3.index = [0, 2, 5, 7]
print(df1)
print(df2)
print(df3)

    A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1
2  a2  b2  c2  d2
3  a3  b3  c3  d3
    E   F   G   H
4  a4  b4  c4  d4
5  a5  b5  c5  d5
6  a6  b6  c6  d6
7  a7  b7  c7  d7
     A    C    F    H
0   a8   b8   c8   d8
2   a9   b9   c9   d9
5  a10  b10  c10  d10
7  a11  b11  c11  d11

In [52]:
col_concat = pd.concat([df1, df2, df3], axis="columns", join="outer")
print(col_concat)

     A    B    C    D    E    F    G    H    A    C    F    H
0   a0   b0   c0   d0  NaN  NaN  NaN  NaN   a8   b8   c8   d8
1   a1   b1   c1   d1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   a2   b2   c2   d2  NaN  NaN  NaN  NaN   a9   b9   c9   d9
3   a3   b3   c3   d3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN   a4   b4   c4   d4  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN   a5   b5   c5   d5  a10  b10  c10  d10
6  NaN  NaN  NaN  NaN   a6   b6   c6   d6  NaN  NaN  NaN  NaN
7  NaN  NaN  NaN  NaN   a7   b7   c7   d7  a11  b11  c11  d11

In [56]:
person = pd.read_csv('./data/survey_person.csv')
site = pd.read_csv('./data/survey_site.csv')
survey = pd.read_csv('./data/survey_survey.csv')
visited = pd.read_csv('./data/survey_visited.csv')
print(person)
print(site)
print(survey)
print(visited)

      ident   personal    family
0      dyer    William      Dyer
1        pb      Frank   Pabodie
2      lake   Anderson      Lake
3       roe  Valentina   Roerich
4  danforth      Frank  Danforth
    name    lat    long
0   DR-1 -49.85 -128.57
1   DR-3 -47.15 -126.72
2  MSK-4 -48.87 -123.40
    taken person quant  reading
0     619   dyer   rad     9.82
1     619   dyer   sal     0.13
2     622   dyer   rad     7.80
3     622   dyer   sal     0.09
4     734     pb   rad     8.41
5     734   lake   sal     0.05
6     734     pb  temp   -21.50
7     735     pb   rad     7.22
8     735    NaN   sal     0.06
9     735    NaN  temp   -26.00
10    751     pb   rad     4.35
11    751     pb  temp   -18.50
12    751   lake   sal     0.10
13    752   lake   rad     2.19
14    752   lake   sal     0.09
15    752   lake  temp   -16.00
16    752    roe   sal    41.60
17    837   lake   rad     1.46
18    837   lake   sal     0.21
19    837    roe   sal    22.50
20    844    roe   rad    11.25
   ident   site       dated
0    619   DR-1  1927-02-08
1    622   DR-1  1927-02-10
2    734   DR-3  1939-01-07
3    735   DR-3  1930-01-12
4    751   DR-3  1930-02-26
5    752   DR-3         NaN
6    837  MSK-4  1932-01-14
7    844   DR-1  1932-03-22

In [59]:
visited_subset = visited.loc[[0, 2], :]
print(visited_subset)

   ident  site       dated
0    619  DR-1  1927-02-08
2    734  DR-3  1939-01-07

In [66]:
o2o_merge = site.merge(visited_subset, 
                       left_on="name", right_on="site",
                      how="outer")
print(o2o_merge)

    name    lat    long  ident  site       dated
0   DR-1 -49.85 -128.57  619.0  DR-1  1927-02-08
1   DR-3 -47.15 -126.72  734.0  DR-3  1939-01-07
2  MSK-4 -48.87 -123.40    NaN   NaN         NaN

In [122]:
# 연습 문제
import pandas as pd
customers = pd.DataFrame({
    'customers_id': [1,2,3,4],
    'name': ['Alice', 'Bob', 'Charlie', 'David']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103],
    'customer_id': [1, 2, 5],
    'amount': [25000, 45000, 30000]
})
print(customers)
orders

   customers_id     name
0             1    Alice
1             2      Bob
2             3  Charlie
3             4    David

   order_id  customer_id  amount
0       101            1   25000
1       102            2   45000
2       103            5   30000

In [125]:
# 기본 레벨
# 답안
# result = pd.merge(customers, orders, on='customer_id', how='inner')

df= customers.merge(
    orders,
    left_on="customers_id",
    right_on="customer_id",
    how="inner").drop(columns=["customer_id"])

print(df)

   customers_id   name  order_id  amount
0             1  Alice       101   25000
1             2    Bob       102   45000

In [129]:
# 문제 2
# 답안
# result = pd.merge(customers, orders, on='customer_id', how='left')

df2 = customers.merge(
    orders,
    left_on="customers_id",
    right_on="customer_id",
    how="left").drop(columns=["customer_id"])

print(df2)

   customers_id     name  order_id   amount
0             1    Alice     101.0  25000.0
1             2      Bob     102.0  45000.0
2             3  Charlie       NaN      NaN
3             4    David       NaN      NaN

In [133]:
# 문제 3
# 답안
# result = pd.merge(customers, orders, on='customer_id', how='right')

df3 = customers.merge(
    orders,
    left_on="customers_id",
    right_on="customer_id",
    how="right").drop(columns=["customer_id"])

print(df3)

   customers_id   name  order_id  amount
0           1.0  Alice       101   25000
1           2.0    Bob       102   45000
2           NaN    NaN       103   30000

In [110]:
# 중급 레벨 데이터
jan_fales = pd.DataFrame({
    'product_id': ['P001','P002','P003'],
    'jan_amount': [1000, 2000, 1500]
})

feb_sales = pd.DataFrame({
    'product_id': ['P002','P003','P004'],
    'feb_amount': [2200, 1400, 3000]
})

print(jan_fales)
feb_sales

  product_id  jan_amount
0       P001        1000
1       P002        2000
2       P003        1500

  product_id  feb_amount
0       P002        2200
1       P003        1400
2       P004        3000

In [131]:
# 중급 레벨 답안
jan_sales = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003'],
    'jan_amount': [1000, 2000, 1500]
})

feb_sales = pd.DataFrame({
    'product_id': ['P002', 'P003', 'P004'],
    'feb_amount': [2200, 1400, 3000]
})

result = pd.merge(jan_sales, feb_sales, on='product_id', how='outer')
result = result.fillna(0)
result['total'] = result['jan_amount'] + result['feb_amount']
print(result)

  product_id  jan_amount  feb_amount   total
0       P001      1000.0         0.0  1000.0
1       P002      2000.0      2200.0  4200.0
2       P003      1500.0      1400.0  2900.0
3       P004         0.0      3000.0  3000.0

In [108]:
# 중급 레벨
df = pd.merge(jan_fales, feb_sales, on='product_id', how='outer')

df[['jan_amount', 'feb_amount']] = df[['jan_amount', 'feb_amount']].fillna(0)

# total 컬럼 생성
df['total'] = df['jan_amount'] + df['feb_amount']

print(df)

  product_id  jan_amount  feb_amount   total
0       P001      1000.0         0.0  1000.0
1       P002      2000.0      2200.0  4200.0
2       P003      1500.0      1400.0  2900.0
3       P004         0.0      3000.0  3000.0

In [111]:
# 고급 레벨 데이터
online = pd.DataFrame({
    'customer_id': ['C001', 'C002', 'C003', 'C004'],
    'name': ['홍길동', '김철수', '이영희', '박민수'],
    'email': ['hong@test.com', 'kim@test.com', 'lee@test.com', 'park@test.com'],
    'join_date': ['2023-01-15', '2023-03-20', '2023-06-10', '2023-08-05'],
    'total_purchase': [500000, 1200000, 800000, 0]
})

grades = pd.DataFrame({
    'customer_id': ['C001', 'C002', 'C003', 'C005'],
    'grade': ['Silver', 'Gold', 'Gold', 'Silver'],
    'points': [500, 1500, 1200, 600]
})

print(online)
grades

  customer_id name          email   join_date  total_purchase
0        C001  홍길동  hong@test.com  2023-01-15          500000
1        C002  김철수   kim@test.com  2023-03-20         1200000
2        C003  이영희   lee@test.com  2023-06-10          800000
3        C004  박민수  park@test.com  2023-08-05               0

  customer_id   grade  points
0        C001  Silver     500
1        C002    Gold    1500
2        C003    Gold    1200
3        C005  Silver     600

In [132]:
# 고급 레벨 답안
online = pd.DataFrame({
    'customer_id': ['C001', 'C002', 'C003', 'C004'],
    'name': ['홍길동', '김철수', '이영희', '박민수'],
    'email': ['hong@test.com', 'kim@test.com', 'lee@test.com', 'park@test.com'],
    'join_date': ['2023-01-15', '2023-03-20', '2023-06-10', '2023-08-05'],
    'total_purchase': [500000, 1200000, 800000, 0]
})

grades = pd.DataFrame({
    'customer_id': ['C001', 'C002', 'C003', 'C005'],
    'grade': ['Silver', 'Gold', 'Gold', 'Silver'],
    'points': [500, 1500, 1200, 600]
})

result = pd.merge(online, grades, on='customer_id', how='left')
result['grade'] = result['grade'].fillna('Unknown')
print(result)

# 등급별 평균 total_purchase
print(result.groupby('grade')['total_purchase'].mean())

  customer_id name          email   join_date  total_purchase    grade  points
0        C001  홍길동  hong@test.com  2023-01-15          500000   Silver   500.0
1        C002  김철수   kim@test.com  2023-03-20         1200000     Gold  1500.0
2        C003  이영희   lee@test.com  2023-06-10          800000     Gold  1200.0
3        C004  박민수  park@test.com  2023-08-05               0  Unknown     NaN
grade
Gold       1000000.0
Silver      500000.0
Unknown          0.0
Name: total_purchase, dtype: float64