In [7]:
import pandas as pd
df = pd.read_csv("./Data/oil_sell.csv", encoding="cp949")
# cp949 - ms에서 만든 확장완성형 코드셋(사전에 없는 글자를 정의한 코드셋
# ksc5601 - 유가데이터, 변환 필요 (한글전용(상용한글, 한글사전)
# utf8 - 유니코드(전세계 용어를 하나로 정의한 코드셋

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260330,HD현대오일뱅크,셀프,2190,1848,1834,0
1,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260331,HD현대오일뱅크,셀프,2258,1868,1854,0
2,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260401,HD현대오일뱅크,셀프,2358,1893,1879,0
3,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260402,HD현대오일뱅크,셀프,2358,1934,1923,0
4,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260403,HD현대오일뱅크,셀프,2358,1934,1923,0
...,...,...,...,...,...,...,...,...,...,...,...
72565,A0013418,충북 충주시,희망주유소,충북 충주시 금봉대로 398,20260401,GS칼텍스,셀프,0,1898,1898,1450
72566,A0013418,충북 충주시,희망주유소,충북 충주시 금봉대로 398,20260402,GS칼텍스,셀프,0,1898,1898,1450
72567,A0013418,충북 충주시,희망주유소,충북 충주시 금봉대로 398,20260403,GS칼텍스,셀프,0,1948,1948,1450
72568,A0013418,충북 충주시,희망주유소,충북 충주시 금봉대로 398,20260404,GS칼텍스,셀프,0,1948,1948,1450
72569,A0013418,충북 충주시,희망주유소,충북 충주시 금봉대로 398,20260405,GS칼텍스,셀프,0,1948,1948,1450

In [13]:
print(df.shape)
print(df.shape[0])
(f"열 갯수는 {df.shape[1]}")

(72570, 11)
72570

'열 갯수는 11'

In [15]:
df.columns

Index(['번호', '지역', '상호', '주소', '기간', '상표', '셀프여부', '고급휘발유', '휘발유', '경유',
       '실내등유'],
      dtype='object')

In [16]:
df.index

RangeIndex(start=0, stop=72570, step=1)

In [17]:
df.dtypes

번호       object
지역       object
상호       object
주소       object
기간        int64
상표       object
셀프여부     object
고급휘발유     int64
휘발유       int64
경유        int64
실내등유      int64
dtype: object

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72570 entries, 0 to 72569
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      72570 non-null  object
 1   지역      72570 non-null  object
 2   상호      72570 non-null  object
 3   주소      72570 non-null  object
 4   기간      72570 non-null  int64
 5   상표      72570 non-null  object
 6   셀프여부    72570 non-null  object
 7   고급휘발유   72570 non-null  int64
 8   휘발유     72570 non-null  int64
 9   경유      72570 non-null  int64
 10  실내등유    72570 non-null  int64
dtypes: int64(5), object(6)
memory usage: 6.1+ MB

In [19]:
df.head(3)

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
0,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260330,HD현대오일뱅크,셀프,2190,1848,1834,0
1,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260331,HD현대오일뱅크,셀프,2258,1868,1854,0
2,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260401,HD현대오일뱅크,셀프,2358,1893,1879,0

In [20]:
df.tail(2)

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
72568,A0013418,충북 충주시,희망주유소,충북 충주시 금봉대로 398,20260404,GS칼텍스,셀프,0,1948,1948,1450
72569,A0013418,충북 충주시,희망주유소,충북 충주시 금봉대로 398,20260405,GS칼텍스,셀프,0,1948,1948,1450

In [24]:
df['상호'].unique() #칼럼 이름이 한글일 경우, .제거, 대괄호 씌워주기

array(['(주)강릉햇살 유천주유소', '(주)대성길', '(주)명진에너지 북강릉지점', ..., '충주주유소', '해운주유소',
       '화령개발(주)공단주유소'], shape=(8340,), dtype=object)

In [25]:
df['지역']

0        강원 강릉시
1        강원 강릉시
2        강원 강릉시
3        강원 강릉시
4        강원 강릉시
          ...
72565    충북 충주시
72566    충북 충주시
72567    충북 충주시
72568    충북 충주시
72569    충북 충주시
Name: 지역, Length: 72570, dtype: object

In [26]:
df[['지역']]

           지역
0      강원 강릉시
1      강원 강릉시
2      강원 강릉시
3      강원 강릉시
4      강원 강릉시
...       ...
72565  충북 충주시
72566  충북 충주시
72567  충북 충주시
72568  충북 충주시
72569  충북 충주시

[72570 rows x 1 columns]

In [27]:
df.loc[50]

번호                  A0011490
지역                    강원 강릉시
상호       HD현대오일뱅크㈜직영 강릉IC주유소
주소           강원 강릉시 경강로 1935
기간                  20260331
상표                  HD현대오일뱅크
셀프여부                      일반
고급휘발유                   1970
휘발유                     1785
경유                      1747
실내등유                    1490
Name: 50, dtype: object

In [28]:
df.loc[50]['상표']

'HD현대오일뱅크'

In [30]:
df.loc[[4,7,8]]

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
4,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260403,HD현대오일뱅크,셀프,2358,1934,1923,0
7,A0011352,강원 강릉시,(주)대성길,강원 강릉시 구정면 칠성로 187,20260330,S-OIL,셀프,0,1858,1858,1500
8,A0011352,강원 강릉시,(주)대성길,강원 강릉시 구정면 칠성로 187,20260331,S-OIL,셀프,0,1990,1990,1600

In [32]:
df.loc[[4,7,8]]['상호']

4    (주)강릉햇살 유천주유소
7           (주)대성길
8           (주)대성길
Name: 상호, dtype: object

In [31]:
df.loc[[7,8,4]]

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
7,A0011352,강원 강릉시,(주)대성길,강원 강릉시 구정면 칠성로 187,20260330,S-OIL,셀프,0,1858,1858,1500
8,A0011352,강원 강릉시,(주)대성길,강원 강릉시 구정면 칠성로 187,20260331,S-OIL,셀프,0,1990,1990,1600
4,A0033584,강원 강릉시,(주)강릉햇살 유천주유소,강원도 강릉시 사임당로 178(유천동),20260403,HD현대오일뱅크,셀프,2358,1934,1923,0

In [34]:
df.loc[[7,8,4]].iloc[1]

번호                 A0011352
지역                   강원 강릉시
상호                   (주)대성길
주소       강원 강릉시 구정면 칠성로 187
기간                 20260331
상표                    S-OIL
셀프여부                     셀프
고급휘발유                     0
휘발유                    1990
경유                     1990
실내등유                   1600
Name: 8, dtype: object

In [35]:
df.loc[[7,8,4]].iloc[1]['지역']

'강원 강릉시'

In [36]:
df.iloc[-1]

번호              A0013418
지역                충북 충주시
상호                 희망주유소
주소       충북 충주시 금봉대로 398
기간              20260405
상표                 GS칼텍스
셀프여부                  셀프
고급휘발유                  0
휘발유                 1948
경유                  1948
실내등유                1450
Name: 72569, dtype: object

In [37]:
df.iloc[-1]['주소']

'충북 충주시 금봉대로 398'

In [47]:
df.loc[[333,1234,1500],['지역','상호','주소']]

          지역       상호                       주소
333   강원 강릉시   소금강주유소  강원 강릉시 연곡면 삼산리 진고개로1515
1234  강원 양구군  배꼽셀프주유소   강원 양구군 국토정중앙면 춘양로 2894
1500  강원 영월군  오일세상주유소        강원 영월군 북면 원동재로 98

In [57]:
df.loc[ :, '상호'] #모든 열의 상호
df.loc[  365:, '상호'] #365열부터 마지막열까지
df.loc[ 2128:8535, '상호'] #2128열부터 8535열까지
df.loc[ :4, '상호'] #첫 열~4열까지
df.loc[ :4, '상호':'주소'] #첫 열~4열까지 상호부터 주소까지
df.loc[ [7777,34545,8854], '지역':'주소'] #세개행 지역부터 주소까지

            지역     상호                    주소
7777   경기 동두천시  이섬주유소  경기 동두천시 어수로 30 (상패동)
34545   광주 광산구  대천주유소        광주 광산구 용진로 599
8854    경기 수원시  서부주유소    경기 수원시 팔달구 수성로 188

In [74]:
# b1 = df['경유'] < 1800
# df.loc[b1]
df[(df['경유'] < 1800) & (df['경유'] != 0)]

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
49,A0011490,강원 강릉시,HD현대오일뱅크㈜직영 강릉IC주유소,강원 강릉시 경강로 1935,20260330,HD현대오일뱅크,일반,1970,1785,1747,1490
50,A0011490,강원 강릉시,HD현대오일뱅크㈜직영 강릉IC주유소,강원 강릉시 경강로 1935,20260331,HD현대오일뱅크,일반,1970,1785,1747,1490
51,A0011490,강원 강릉시,HD현대오일뱅크㈜직영 강릉IC주유소,강원 강릉시 경강로 1935,20260401,HD현대오일뱅크,일반,2019,1785,1747,1490
52,A0011490,강원 강릉시,HD현대오일뱅크㈜직영 강릉IC주유소,강원 강릉시 경강로 1935,20260402,HD현대오일뱅크,일반,2019,1785,1747,1490
53,A0011490,강원 강릉시,HD현대오일뱅크㈜직영 강릉IC주유소,강원 강릉시 경강로 1935,20260403,HD현대오일뱅크,일반,2114,1785,1747,1490
...,...,...,...,...,...,...,...,...,...,...,...
72038,A0013227,충북 충주시,HD현대오일뱅크㈜직영 충원대로주유소,충북 충주시 충원대로 1020,20260330,HD현대오일뱅크,일반,2053,1768,1759,1490
72039,A0013227,충북 충주시,HD현대오일뱅크㈜직영 충원대로주유소,충북 충주시 충원대로 1020,20260331,HD현대오일뱅크,일반,2093,1768,1759,1490
72040,A0013227,충북 충주시,HD현대오일뱅크㈜직영 충원대로주유소,충북 충주시 충원대로 1020,20260401,HD현대오일뱅크,일반,2093,1768,1759,1490
72041,A0013227,충북 충주시,HD현대오일뱅크㈜직영 충원대로주유소,충북 충주시 충원대로 1020,20260402,HD현대오일뱅크,일반,2183,1768,1759,1490
72042,A0013227,충북 충주시,HD현대오일뱅크㈜직영 충원대로주유소,충북 충주시 충원대로 1020,20260403,HD현대오일뱅크,일반,2280,1768,1759,1490

In [82]:
r1 = df['주소'].str.contains("용인시 처인구 포곡읍")
df.loc[r1]

,번호,지역,상호,주소,기간,상표,셀프여부,고급휘발유,휘발유,경유,실내등유
13233,A0008914,경기 용인시,HD현대오일뱅크㈜직영 에버랜드주유소,경기 용인시 처인구 포곡읍 에버랜드로 184,20260330,HD현대오일뱅크,일반,2320,1788,1749,1579
13234,A0008914,경기 용인시,HD현대오일뱅크㈜직영 에버랜드주유소,경기 용인시 처인구 포곡읍 에버랜드로 184,20260331,HD현대오일뱅크,일반,2320,1788,1749,1579
13235,A0008914,경기 용인시,HD현대오일뱅크㈜직영 에버랜드주유소,경기 용인시 처인구 포곡읍 에버랜드로 184,20260401,HD현대오일뱅크,일반,2320,1788,1749,1579
13236,A0008914,경기 용인시,HD현대오일뱅크㈜직영 에버랜드주유소,경기 용인시 처인구 포곡읍 에버랜드로 184,20260402,HD현대오일뱅크,일반,2320,1788,1749,1579
13237,A0008914,경기 용인시,HD현대오일뱅크㈜직영 에버랜드주유소,경기 용인시 처인구 포곡읍 에버랜드로 184,20260403,HD현대오일뱅크,일반,2395,1788,1749,1579
...,...,...,...,...,...,...,...,...,...,...,...
14374,A0008932,경기 용인시,희망주유소,경기 용인시 처인구 포곡읍 백옥대로 1924-10,20260401,S-OIL,셀프,2250,1915,1895,1550
14375,A0008932,경기 용인시,희망주유소,경기 용인시 처인구 포곡읍 백옥대로 1924-10,20260402,S-OIL,셀프,2250,1915,1895,1550
14376,A0008932,경기 용인시,희망주유소,경기 용인시 처인구 포곡읍 백옥대로 1924-10,20260403,S-OIL,셀프,2250,1915,1895,1550
14377,A0008932,경기 용인시,희망주유소,경기 용인시 처인구 포곡읍 백옥대로 1924-10,20260404,S-OIL,셀프,2250,1945,1920,1550
14378,A0008932,경기 용인시,희망주유소,경기 용인시 처인구 포곡읍 백옥대로 1924-10,20260405,S-OIL,셀프,2250,1945,1920,1550

In [83]:
df.describe()

                 기간         고급휘발유           휘발유            경유          실내등유
count  7.257000e+04  72570.000000  72570.000000  72570.000000  72570.000000
mean   2.026038e+07    421.553838   1908.114028   1907.858137    882.977374
std    3.278102e+01    874.667880    154.923234     90.269533    774.771773
min    2.026033e+07      0.000000      0.000000      0.000000      0.000000
25%    2.026033e+07      0.000000   1875.000000   1869.000000      0.000000
50%    2.026040e+07      0.000000   1912.000000   1899.000000   1450.000000
75%    2.026040e+07      0.000000   1965.000000   1955.000000   1560.000000
max    2.026040e+07   2980.000000   2498.000000   2398.000000   2150.000000

In [103]:
df.groupby('휘발유')['경유'].mean()

휘발유
0       1744.593909
1625    1909.000000
1744    1714.000000
1749    1723.090909
1750    1800.000000
           ...
2389    2279.000000
2390    2308.571429
2398    2398.000000
2489    2379.000000
2498    2240.000000
Name: 경유, Length: 368, dtype: float64

In [104]:
df.groupby('휘발유')['고급휘발유'].mean()

휘발유
0        194.022843
1625    2339.000000
1744       0.000000
1749     944.545455
1750       0.000000
           ...
2389    2572.333333
2390    2915.428571
2398    2505.272727
2489    2689.000000
2498    2798.000000
Name: 고급휘발유, Length: 368, dtype: float64